
emails := []
emails.Push("https://www.tjsc.jus.br/comarcas/abelardo-luz")
emails.Push("https://www.tjsc.jus.br/comarcas/anchieta")
emails.Push("https://www.tjsc.jus.br/comarcas/anita-garibaldi")
emails.Push("https://www.tjsc.jus.br/comarcas/araquari")
emails.Push("https://www.tjsc.jus.br/comarcas/ararangua")
emails.Push("https://www.tjsc.jus.br/comarcas/armazem")
emails.Push("https://www.tjsc.jus.br/comarcas/ascurra")
emails.Push("https://www.tjsc.jus.br/comarcas/balneario-camboriu")
emails.Push("https://www.tjsc.jus.br/comarcas/balneario-picarras")
emails.Push("https://www.tjsc.jus.br/comarcas/barra-velha")
emails.Push("https://www.tjsc.jus.br/comarcas/biguacu")
emails.Push("https://www.tjsc.jus.br/comarcas/blumenau")
emails.Push("https://www.tjsc.jus.br/comarcas/blumenau-forum-universitario")
emails.Push("https://www.tjsc.jus.br/comarcas/bom-retiro")
emails.Push("https://www.tjsc.jus.br/comarcas/braco-do-norte")
emails.Push("https://www.tjsc.jus.br/comarcas/brusque")
emails.Push("https://www.tjsc.jus.br/comarcas/cacador")
emails.Push("https://www.tjsc.jus.br/comarcas/camboriu")
emails.Push("https://www.tjsc.jus.br/comarcas/campo-belo-do-sul")
emails.Push("https://www.tjsc.jus.br/comarcas/campo-ere")
emails.Push("https://www.tjsc.jus.br/comarcas/campos-novos")
emails.Push("https://www.tjsc.jus.br/comarcas/canoinhas")
emails.Push("https://www.tjsc.jus.br/comarcas/capinzal")
emails.Push("https://www.tjsc.jus.br/comarcas/capital")
emails.Push("https://www.tjsc.jus.br/comarcas/capital-continente")
emails.Push("https://www.tjsc.jus.br/comarcas/capital-forum-direito-bancario")
emails.Push("https://www.tjsc.jus.br/comarcas/capital-forum-eduardo-luz")
emails.Push("https://www.tjsc.jus.br/comarcas/capital-norte-da-ilha")
emails.Push("https://www.tjsc.jus.br/comarcas/capivari-de-baixo")
emails.Push("https://www.tjsc.jus.br/comarcas/catanduvas")
emails.Push("https://www.tjsc.jus.br/comarcas/chapeco")
emails.Push("https://www.tjsc.jus.br/comarcas/concordia")
emails.Push("https://www.tjsc.jus.br/comarcas/coronel-freitas")
emails.Push("https://www.tjsc.jus.br/comarcas/correia-pinto")
emails.Push("https://www.tjsc.jus.br/comarcas/criciuma")
emails.Push("https://www.tjsc.jus.br/comarcas/cunha-pora")
emails.Push("https://www.tjsc.jus.br/comarcas/curitibanos")
emails.Push("https://www.tjsc.jus.br/comarcas/descanso")
emails.Push("https://www.tjsc.jus.br/comarcas/dionisio-cerqueira")
emails.Push("https://www.tjsc.jus.br/comarcas/forquilhinha")
emails.Push("https://www.tjsc.jus.br/comarcas/fraiburgo")
emails.Push("https://www.tjsc.jus.br/comarcas/garopaba")
emails.Push("https://www.tjsc.jus.br/comarcas/garuva")
emails.Push("https://www.tjsc.jus.br/comarcas/gaspar")
emails.Push("https://www.tjsc.jus.br/comarcas/guaramirim")
emails.Push("https://www.tjsc.jus.br/comarcas/herval-d-oeste")
emails.Push("https://www.tjsc.jus.br/comarcas/ibirama")
emails.Push("https://www.tjsc.jus.br/comarcas/icara")
emails.Push("https://www.tjsc.jus.br/comarcas/imarui")
emails.Push("https://www.tjsc.jus.br/comarcas/imbituba")
emails.Push("https://www.tjsc.jus.br/comarcas/indaial")
emails.Push("https://www.tjsc.jus.br/comarcas/ipumirim")
emails.Push("https://www.tjsc.jus.br/comarcas/ita")
emails.Push("https://www.tjsc.jus.br/comarcas/itaiopolis")
emails.Push("https://www.tjsc.jus.br/comarcas/itajai")
emails.Push("https://www.tjsc.jus.br/comarcas/itapema")
emails.Push("https://www.tjsc.jus.br/comarcas/itapiranga")
emails.Push("https://www.tjsc.jus.br/comarcas/itapoa")
emails.Push("https://www.tjsc.jus.br/comarcas/ituporanga")
emails.Push("https://www.tjsc.jus.br/comarcas/jaguaruna")
emails.Push("https://www.tjsc.jus.br/comarcas/jaragua-do-sul")
emails.Push("https://www.tjsc.jus.br/comarcas/joacaba")
emails.Push("https://www.tjsc.jus.br/comarcas/joinville")
emails.Push("https://www.tjsc.jus.br/comarcas/joinville-forum-fazendario")
emails.Push("https://www.tjsc.jus.br/comarcas/lages")
emails.Push("https://www.tjsc.jus.br/comarcas/laguna")
emails.Push("https://www.tjsc.jus.br/comarcas/lauro-muller")
emails.Push("https://www.tjsc.jus.br/comarcas/lebon-regis")
emails.Push("https://www.tjsc.jus.br/comarcas/mafra")
emails.Push("https://www.tjsc.jus.br/comarcas/maravilha")
emails.Push("https://www.tjsc.jus.br/comarcas/meleiro")
emails.Push("https://www.tjsc.jus.br/comarcas/modelo")
emails.Push("https://www.tjsc.jus.br/comarcas/mondai")
emails.Push("https://www.tjsc.jus.br/comarcas/navegantes")
emails.Push("https://www.tjsc.jus.br/comarcas/orleans")
emails.Push("https://www.tjsc.jus.br/comarcas/otacilio-costa")
emails.Push("https://www.tjsc.jus.br/comarcas/palhoca")
emails.Push("https://www.tjsc.jus.br/comarcas/palmitos")
emails.Push("https://www.tjsc.jus.br/comarcas/papanduva")
emails.Push("https://www.tjsc.jus.br/comarcas/pinhalzinho")
emails.Push("https://www.tjsc.jus.br/comarcas/pomerode")
emails.Push("https://www.tjsc.jus.br/comarcas/ponte-serrada")
emails.Push("https://www.tjsc.jus.br/comarcas/porto-belo")
emails.Push("https://www.tjsc.jus.br/comarcas/porto-uniao")
emails.Push("https://www.tjsc.jus.br/comarcas/presidente-getulio")
emails.Push("https://www.tjsc.jus.br/comarcas/quilombo")
emails.Push("https://www.tjsc.jus.br/comarcas/rio-do-campo")
emails.Push("https://www.tjsc.jus.br/comarcas/rio-do-oeste")
emails.Push("https://www.tjsc.jus.br/comarcas/rio-do-sul")
emails.Push("https://www.tjsc.jus.br/comarcas/rio-negrinho")
emails.Push("https://www.tjsc.jus.br/comarcas/santa-cecilia")
emails.Push("https://www.tjsc.jus.br/comarcas/santa-rosa-do-sul")
emails.Push("https://www.tjsc.jus.br/comarcas/santo-amaro-da-imperatriz")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-bento-do-sul")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-carlos")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-domingos")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-francisco-do-sul")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-joao-batista")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-joaquim")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-jose")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-jose-do-cedro")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-lourenco-do-oeste")
emails.Push("https://www.tjsc.jus.br/comarcas/sao-miguel-do-oeste")
emails.Push("https://www.tjsc.jus.br/comarcas/seara")
emails.Push("https://www.tjsc.jus.br/comarcas/sombrio")
emails.Push("https://www.tjsc.jus.br/comarcas/taio")
emails.Push("https://www.tjsc.jus.br/comarcas/tangara")
emails.Push("https://www.tjsc.jus.br/comarcas/tijucas")
emails.Push("https://www.tjsc.jus.br/comarcas/timbo")
emails.Push("https://www.tjsc.jus.br/comarcas/trombudo-central")
emails.Push("https://www.tjsc.jus.br/comarcas/tubarao")
emails.Push("https://www.tjsc.jus.br/comarcas/turvo")
emails.Push("https://www.tjsc.jus.br/comarcas/urubici")
emails.Push("https://www.tjsc.jus.br/comarcas/urussanga")
emails.Push("https://www.tjsc.jus.br/comarcas/videira")
emails.Push("https://www.tjsc.jus.br/comarcas/xanxere")
emails.Push("https://www.tjsc.jus.br/comarcas/xaxim")

contador := 0
Loop % emails.MaxIndex()
{
Run ,% emails[A_Index]
sleep 2000 
Send, ^+i
sleep 2000 
Send, {Tab 1}
SendInput, {Raw} function getEmails() {var search_in = document.body.innerHTML;string_context = search_in.toString();array_mails = string_context.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/gi);return array_mails;}let emails = getEmails();copy(emails);
Send, {Enter}
sleep 5000 
WinActivate, ahk_class Notepad
Send, ^v
Send,{Enter}
if (contador < 15){
    contador := contador + 1
} else{
    contador := 0
    WinClose, ahk_exe msedge.exe

}
}

Return