#SingleInstance, Force


words := []

words.Push("abelar")
words.Push("luz")
words.Push("anchieta")
words.Push("anita")
words.Push("garibaldi")
words.Push("araquari")
words.Push("ararangua")
words.Push("armazem")
words.Push("ascurra")
words.Push("balneario")
words.Push("camboriu")
words.Push("balneario")
words.Push("picarras")
words.Push("barra")
words.Push("velha")
words.Push("biguacu")
words.Push("blumenau")
words.Push("blumenau")
words.Push("forum")
words.Push("universitario")
words.Push("bom")
words.Push("retiro")
words.Push("braco")
words.Push("norte")
words.Push("brusque")
words.Push("cacar")
words.Push("camboriu")
words.Push("campo")
words.Push("belo")
words.Push("sul")
words.Push("campo")
words.Push("ere")
words.Push("campos")
words.Push("novos")
words.Push("canoinhas")
words.Push("capinzal")
words.Push("capital")
words.Push("capital")
words.Push("continente")
words.Push("capital")
words.Push("forum")
words.Push("direito")
words.Push("bancario")
words.Push("capital")
words.Push("forum")
words.Push("eduar")
words.Push("luz")
words.Push("capital")
words.Push("norte")
words.Push("da")
words.Push("ilha")
words.Push("capivari")
words.Push("de")
words.Push("baixo")
words.Push("catanduvas")
words.Push("chapeco")
words.Push("concordia")
words.Push("coronel")
words.Push("freitas")
words.Push("correia")
words.Push("pinto")
words.Push("criciuma")
words.Push("cunha")
words.Push("pora")
words.Push("curitibanos")
words.Push("descanso")
words.Push("dionisio")
words.Push("cerqueira")
words.Push("forquilhinha")
words.Push("fraiburgo")
words.Push("garopaba")
words.Push("garuva")
words.Push("gaspar")
words.Push("guaramirim")
words.Push("herval")
words.Push("oeste")
words.Push("ibirama")
words.Push("icara")
words.Push("imarui")
words.Push("imbituba")
words.Push("indaial")
words.Push("ipumirim")
words.Push("ita")
words.Push("itaiopolis")
words.Push("itajai")
words.Push("itapema")
words.Push("itapiranga")
words.Push("itapoa")
words.Push("ituporanga")
words.Push("jaguaruna")
words.Push("jaragua")
words.Push("sul")
words.Push("joacaba")
words.Push("joinville")
words.Push("joinville")
words.Push("forum")
words.Push("fazendario")
words.Push("lages")
words.Push("laguna")
words.Push("lauro")
words.Push("muller")
words.Push("lebon")
words.Push("regis")
words.Push("mafra")
words.Push("maravilha")
words.Push("meleiro")
words.Push("modelo")
words.Push("mondai")
words.Push("navegantes")
words.Push("orleans")
words.Push("otacilio")
words.Push("costa")
words.Push("palhoca")
words.Push("palmitos")
words.Push("papanduva")
words.Push("pinhalzinho")
words.Push("pomerode")
words.Push("ponte")
words.Push("serrada")
words.Push("porto")
words.Push("belo")
words.Push("porto")
words.Push("uniao")
words.Push("presidente")
words.Push("getulio")
words.Push("quilombo")
words.Push("rio")
words.Push("campo")
words.Push("rio")
words.Push("oeste")
words.Push("rio")
words.Push("sul")
words.Push("rio")
words.Push("negrinho")
words.Push("santa")
words.Push("cecilia")
words.Push("santa")
words.Push("rosa")
words.Push("sul")
words.Push("santo")
words.Push("amaro")
words.Push("da")
words.Push("imperatriz")
words.Push("sao")
words.Push("bento")
words.Push("sul")
words.Push("sao")
words.Push("carlos")
words.Push("sao")
words.Push("mingos")
words.Push("sao")
words.Push("francisco")
words.Push("sul")
words.Push("sao")
words.Push("joao")
words.Push("batista")
words.Push("sao")
words.Push("joaquim")
words.Push("sao")
words.Push("jose")
words.Push("sao")
words.Push("jose")
words.Push("cedro")
words.Push("sao")
words.Push("lourenco")
words.Push("oeste")
words.Push("sao")
words.Push("miguel")
words.Push("oeste")
words.Push("seara")
words.Push("sombrio")
words.Push("taio")
words.Push("tangara")
words.Push("tijucas")
words.Push("timbo")
words.Push("trombu")
words.Push("central")
words.Push("tubarao")
words.Push("turvo")
words.Push("urubici")
words.Push("urussanga")
words.Push("videira")
words.Push("xanxere")
words.Push("xaxim")
words.Push("luz")

DecidirPagina(i){
    return "http://app.tjsc.jus.br/tjsc-consulta-email/#/consultar?nome=" i 
}

GravarEmailsDaPagina(pagina){
    sleep 1000 
    Run , % pagina
    sleep 1000 
    Send, ^+i
    sleep 2000  
    ; Send, {Tab 1}
    SendInput, {Raw} function getEmails() {var search_in = document.body.innerHTML;string_context = search_in.toString();array_mails = string_context.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/gi);return array_mails;}let emails = getEmails();copy(emails);
    Send, {Enter}
    sleep 4000 
    WinActivate, ahk_class Notepad
    Send, ^v
    Send,{Enter}

  
}
for i, word in words
{     
      pagina := DecidirPagina(word)
      GravarEmailsDaPagina(pagina)

}   